package com.hangingspider.game.game

/** Word with its clue — the clue is what makes the game playable. */
data class Word(val text: String, val category: String, val hint: String)

object WordBank {
    private val words = listOf(
        // ---- spider / dark / mystery (thematic core) ----
        Word("SPIDER", "creature", "eight-legged hunter"),
        Word("COBWEB", "spider", "an old abandoned trap"),
        Word("VENOM", "danger", "delivered by a bite"),
        Word("SILK", "spider", "the spider's thread"),
        Word("ARACHNID", "science", "the spider family"),
        Word("FANG", "predator", "a sharp curved tooth"),
        Word("LEGS", "anatomy", "spiders have eight of these"),
        Word("PREY", "hunt", "what the hunter seeks"),
        Word("SPIN", "verb", "what a spider does to a web"),
        Word("NEST", "shelter", "a creature's home"),
        Word("HANGING", "position", "suspended in mid-air"),
        Word("CRAWL", "motion", "how many legs move"),
        Word("WEAVER", "spider", "one who spins a web"),
        Word("MOLTING", "science", "shedding an old skin"),
        Word("BURROW", "shelter", "a tunnel dug for shelter"),
        Word("TALON", "predator", "a bird of prey's grip"),
        Word("MYSTIC", "mystery", "of hidden truths"),
        Word("SHADOW", "darkness", "cast when light is blocked"),
        Word("MIDNIGHT", "time", "the witching hour"),
        Word("PHANTOM", "ghost", "a shadowy presence"),
        Word("WHISPER", "sound", "quiet, almost silent speech"),
        Word("CRYPTIC", "mystery", "hard to decipher"),
        Word("SILENT", "quiet", "making no sound"),
        Word("ECLIPSE", "darkness", "the sun briefly hidden"),
        Word("OMEN", "mystery", "a sign of what is coming"),
        Word("ORACLE", "mystery", "one who foretells fate"),
        Word("RIDDLE", "mystery", "a puzzling question"),
        Word("SPECTRE", "ghost", "a haunting apparition"),
        Word("VOID", "darkness", "an empty, endless space"),
        Word("ABYSS", "darkness", "a chasm without a floor"),
        Word("DUSK", "time", "when day surrenders"),
        Word("HAUNT", "ghost", "to linger where dead once walked"),
        Word("CURSE", "mystery", "a spoken misfortune"),
        Word("RUNE", "mystery", "an ancient carved letter"),
        Word("VEIL", "mystery", "a thin covering of secrecy"),
        Word("MURKY", "darkness", "dim and hard to see through"),
        Word("STALK", "hunt", "to follow patiently"),
        Word("PATIENT", "virtue", "waits without hurry"),
        Word("AMBUSH", "hunt", "a surprise attack from hiding"),
        Word("PROWL", "hunt", "to move stealthily"),
        Word("HUNTER", "hunt", "one who chases prey"),
        Word("SNARE", "hunt", "a rope trap for game"),
        Word("TRAP", "hunt", "waits for the careless"),
        Word("CLAW", "predator", "curved and cutting"),
        Word("BITE", "predator", "closing of the jaws"),
        Word("HOWL", "sound", "a wolf's long cry"),
        Word("STRIKE", "hunt", "a sudden lethal blow"),
        Word("POUNCE", "hunt", "a springing leap onto prey"),
        Word("LURK", "hunt", "to wait unseen"),
        Word("HIDE", "hunt", "to keep out of sight"),
        Word("CHASE", "hunt", "to run after the fleeing"),
        Word("SILENCE", "quiet", "the hunter's cloak"),
        Word("GHOST", "ghost", "a wandering spirit"),
        Word("GRIM", "mood", "stern and forbidding"),
        Word("SPELL", "magic", "words with power"),
        Word("WITCH", "magic", "a caster of hexes"),
        Word("HEX", "magic", "a small curse"),
        Word("CHARM", "magic", "a helpful spell"),
        Word("POTION", "magic", "brewed in a cauldron"),
        Word("WIZARD", "magic", "a master of arcane arts"),
        Word("DRAGON", "creature", "scaled fire-breather"),
        Word("DEMON", "creature", "an evil spirit"),
        Word("SPIRIT", "ghost", "the soul unseen"),
        Word("SKULL", "anatomy", "the head's bone frame"),
        Word("BONE", "anatomy", "hard body scaffold"),
        Word("GRAVE", "death", "a hole for the dead"),
        Word("TOMB", "death", "a stone resting place"),
        Word("COFFIN", "death", "the final wooden box"),
        Word("CRYPT", "death", "underground burial chamber"),
        Word("MORGUE", "death", "where the dead wait"),
        Word("HAUNTED", "ghost", "visited by spirits"),
        Word("ETERNAL", "time", "without end"),
        Word("FATE", "mystery", "what must come"),
        Word("DOOM", "mystery", "a certain dark end"),
        Word("SORROW", "mood", "deep sadness"),
        Word("LAMENT", "sound", "a mournful cry"),
        Word("MOURN", "mood", "to grieve openly"),
        Word("BLEAK", "mood", "cold and hopeless"),
        Word("DREAD", "mood", "fear of what's coming"),

        // ---- creatures / animals ----
        Word("TIGER", "creature", "orange striped hunter"),
        Word("LION", "creature", "the mane-crowned king"),
        Word("BEAR", "creature", "furred forest giant"),
        Word("WOLF", "creature", "howler of the moon"),
        Word("EAGLE", "creature", "soaring raptor"),
        Word("HAWK", "creature", "sharp-eyed hunter of the sky"),
        Word("FALCON", "creature", "the fastest bird"),
        Word("OWL", "creature", "the night's watcher"),
        Word("RAVEN", "creature", "black feathered omen"),
        Word("CROW", "creature", "sooty caller in flocks"),
        Word("SPARROW", "creature", "small brown singer"),
        Word("ROBIN", "creature", "red breast of spring"),
        Word("SWAN", "creature", "long-necked white beauty"),
        Word("DUCK", "creature", "quacking pond swimmer"),
        Word("GOOSE", "creature", "honking traveller"),
        Word("PIGEON", "creature", "city sidewalk bird"),
        Word("PARROT", "creature", "colorful mimic"),
        Word("PENGUIN", "creature", "tuxedo of the ice"),
        Word("FLAMINGO", "creature", "pink one-legged stander"),
        Word("PELICAN", "creature", "pouch-billed diver"),
        Word("HERON", "creature", "still fisher on stilts"),
        Word("STORK", "creature", "long-legged delivery bird"),
        Word("CRANE", "creature", "tall marsh bird"),
        Word("PEACOCK", "creature", "fan of iridescent feathers"),
        Word("BEETLE", "creature", "hard-shell insect"),
        Word("MANTIS", "creature", "praying green predator"),
        Word("SCORPION", "creature", "stinger in the tail"),
        Word("HORNET", "creature", "an angry stinging flyer"),
        Word("WASP", "creature", "yellow-striped stinger"),
        Word("BEE", "creature", "honey-making buzzer"),
        Word("ANT", "creature", "the tiny worker"),
        Word("FLY", "creature", "kitchen bother in summer"),
        Word("MOTH", "creature", "drawn to the flame"),
        Word("BUTTERFLY", "creature", "winged flower dancer"),
        Word("CATERPILLAR", "creature", "the butterfly-to-be"),
        Word("SNAIL", "creature", "carries its house on its back"),
        Word("SLUG", "creature", "shell-less crawler"),
        Word("WORM", "creature", "soft earth-tunneller"),
        Word("HYENA", "creature", "the laughing scavenger"),
        Word("JAGUAR", "creature", "spotted jungle cat"),
        Word("LEOPARD", "creature", "another spotted hunter"),
        Word("CHEETAH", "creature", "the fastest sprinter"),
        Word("PANTHER", "creature", "sleek shadow of the trees"),
        Word("LYNX", "creature", "tufted-ear wildcat"),
        Word("COUGAR", "creature", "mountain lion"),
        Word("FOX", "creature", "clever red-tailed trickster"),
        Word("COYOTE", "creature", "desert dog of moonlight"),
        Word("BADGER", "creature", "stout burrowing brawler"),
        Word("OTTER", "creature", "playful river swimmer"),
        Word("BEAVER", "creature", "toothy dam-builder"),
        Word("SQUIRREL", "creature", "bushy-tailed nut-hider"),
        Word("CHIPMUNK", "creature", "striped tiny cousin"),
        Word("RABBIT", "creature", "long-eared hopper"),
        Word("HARE", "creature", "the swift field-runner"),
        Word("DEER", "creature", "antlered forest walker"),
        Word("MOOSE", "creature", "the great palmate-antlered one"),
        Word("ELK", "creature", "bugling mountain herbivore"),
        Word("REINDEER", "creature", "the caribou of the north"),
        Word("BUFFALO", "creature", "horned plains giant"),
        Word("BISON", "creature", "shaggy prairie roamer"),
        Word("CAMEL", "creature", "the desert humper"),
        Word("HORSE", "creature", "a rider's steed"),
        Word("DONKEY", "creature", "long-eared burden bearer"),
        Word("ZEBRA", "creature", "black and white striped horse"),
        Word("GIRAFFE", "creature", "tallest neck on the plain"),
        Word("ELEPHANT", "creature", "trunked grey giant"),
        Word("RHINO", "creature", "horned charger"),
        Word("HIPPO", "creature", "yawning river monster"),
        Word("KANGAROO", "creature", "pouched hopping outback"),
        Word("KOALA", "creature", "sleeper of the eucalyptus"),
        Word("PANDA", "creature", "black-and-white bamboo lover"),
        Word("SLOTH", "creature", "the slow tree-hanger"),
        Word("MONKEY", "creature", "the swinging cousin"),
        Word("GORILLA", "creature", "silverback of the jungle"),
        Word("CHIMPANZEE", "creature", "tool-using ape"),
        Word("BABOON", "creature", "colored-face troop primate"),
        Word("LEMUR", "creature", "ring-tailed jumper"),
        Word("BAT", "creature", "night-flying mammal"),
        Word("MOUSE", "creature", "cheese-loving squeaker"),
        Word("RAT", "creature", "sewer scavenger"),
        Word("HAMSTER", "creature", "wheel-running pet"),
        Word("GERBIL", "creature", "small pet rodent"),
        Word("HEDGEHOG", "creature", "the prickly one"),
        Word("PORCUPINE", "creature", "quilled slow-mover"),
        Word("SKUNK", "creature", "the sprayer"),
        Word("RACCOON", "creature", "masked bandit"),
        Word("OPOSSUM", "creature", "the playing-dead marsupial"),
        Word("WEASEL", "creature", "slinky little predator"),
        Word("MINK", "creature", "prized-fur hunter"),
        Word("FERRET", "creature", "playful tunneller"),
        Word("SEAL", "creature", "beach-clapping swimmer"),
        Word("WALRUS", "creature", "tusked ice giant"),
        Word("WHALE", "creature", "sea's biggest singer"),
        Word("DOLPHIN", "creature", "clever sea acrobat"),
        Word("ORCA", "creature", "black and white killer"),
        Word("SHARK", "creature", "the sea's toothy patrol"),
        Word("TUNA", "creature", "fast open-ocean fish"),
        Word("SALMON", "creature", "the upstream swimmer"),
        Word("TROUT", "creature", "cold-stream fisherman's prize"),
        Word("PIKE", "creature", "long freshwater predator"),
        Word("BASS", "creature", "sport fisher's staple"),
        Word("CARP", "creature", "the pond bottom-feeder"),
        Word("EEL", "creature", "the slippery snake-fish"),
        Word("SQUID", "creature", "ink-clouding tentacle"),
        Word("OCTOPUS", "creature", "eight-armed intellect"),
        Word("CRAB", "creature", "the side-walker"),
        Word("LOBSTER", "creature", "clawed rock-dweller"),
        Word("SHRIMP", "creature", "tiny curled shellfish"),
        Word("CLAM", "creature", "two-shelled hider"),
        Word("MUSSEL", "creature", "black shelled cluster"),
        Word("OYSTER", "creature", "may hide a pearl"),
        Word("STARFISH", "creature", "five-armed rock cling"),
        Word("JELLYFISH", "creature", "drifting sting"),
        Word("TURTLE", "creature", "the slow-shelled walker"),
        Word("TORTOISE", "creature", "long-lived land turtle"),
        Word("CROCODILE", "creature", "toothy river lurker"),
        Word("ALLIGATOR", "creature", "swamp reptile"),
        Word("LIZARD", "creature", "quick sun-warmed climber"),
        Word("IGUANA", "creature", "spiny tropical lizard"),
        Word("GECKO", "creature", "sticky-footed wall runner"),
        Word("CHAMELEON", "creature", "color-changing tongue-shooter"),
        Word("SNAKE", "creature", "the legless slitherer"),
        Word("COBRA", "creature", "the hooded venom"),
        Word("VIPER", "creature", "quick-strike venom snake"),
        Word("PYTHON", "creature", "the crushing coiler"),
        Word("BOA", "creature", "another squeezing snake"),
        Word("FROG", "creature", "the pond leaper"),
        Word("TOAD", "creature", "warty ground-dweller"),
        Word("NEWT", "creature", "small tailed amphibian"),
        Word("SALAMANDER", "creature", "damp forest crawler"),
        Word("CAT", "creature", "purring house predator"),
        Word("DOG", "creature", "loyal tail-wagger"),
        Word("PUPPY", "creature", "young of the dog"),
        Word("KITTEN", "creature", "young of the cat"),
        Word("POODLE", "creature", "curly-coated pet"),
        Word("BULLDOG", "creature", "stout jowly breed"),
        Word("BEAGLE", "creature", "floppy-eared hound"),
        Word("HUSKY", "creature", "sledge-pulling wolf-alike"),
        Word("TERRIER", "creature", "bold small dog breed"),
        Word("COW", "creature", "pasture milk-giver"),
        Word("BULL", "creature", "horned male cattle"),
        Word("CALF", "creature", "the young cow"),
        Word("PIG", "creature", "curly-tailed grunter"),
        Word("PIGLET", "creature", "small squealer"),
        Word("SHEEP", "creature", "woolly baa-er"),
        Word("LAMB", "creature", "the young sheep"),
        Word("GOAT", "creature", "the horned climber"),
        Word("CHICKEN", "creature", "the barnyard clucker"),
        Word("ROOSTER", "creature", "dawn-crowing bird"),
        Word("HEN", "creature", "layer of eggs"),
        Word("CHICK", "creature", "the fresh-hatched fluff"),
        Word("TURKEY", "creature", "feast day bird"),

        // ---- nature: geography, water, land ----
        Word("RIVER", "nature", "flowing water to the sea"),
        Word("STREAM", "nature", "small flowing water"),
        Word("BROOK", "nature", "small forest stream"),
        Word("CREEK", "nature", "shallow winding water"),
        Word("LAKE", "nature", "large inland water"),
        Word("POND", "nature", "small still water"),
        Word("MARSH", "nature", "wet grassy land"),
        Word("SWAMP", "nature", "muddy tree-filled waters"),
        Word("BOG", "nature", "sinking wet ground"),
        Word("OCEAN", "nature", "the endless sea"),
        Word("SEA", "nature", "salty vast waters"),
        Word("BAY", "nature", "curve of coast"),
        Word("HARBOR", "place", "safe port for ships"),
        Word("BEACH", "nature", "sandy shore"),
        Word("SHORE", "nature", "where land meets water"),
        Word("COAST", "nature", "long line of sea edge"),
        Word("ISLAND", "nature", "surrounded by water"),
        Word("CLIFF", "nature", "steep rock drop"),
        Word("CANYON", "nature", "deep river-cut valley"),
        Word("VALLEY", "nature", "between mountains"),
        Word("GORGE", "nature", "deep narrow ravine"),
        Word("RAVINE", "nature", "sharp deep cut"),
        Word("HILL", "nature", "a small mountain"),
        Word("MOUNTAIN", "nature", "tall rocky peak"),
        Word("PEAK", "nature", "the top of a mountain"),
        Word("SUMMIT", "nature", "the highest point"),
        Word("RIDGE", "nature", "long crest of hills"),
        Word("SLOPE", "nature", "a tilted face"),
        Word("PLATEAU", "nature", "raised flat land"),
        Word("PLAIN", "nature", "wide flat country"),
        Word("MEADOW", "nature", "grassy open field"),
        Word("PASTURE", "nature", "grazing ground"),
        Word("FIELD", "nature", "open cultivable land"),
        Word("PRAIRIE", "nature", "vast grassland"),
        Word("SAVANNA", "nature", "African grass plain"),
        Word("DESERT", "nature", "dry sand country"),
        Word("DUNE", "nature", "wind-piled sand"),
        Word("OASIS", "nature", "water in the desert"),
        Word("JUNGLE", "nature", "dense tropical growth"),
        Word("FOREST", "nature", "a wide gathering of trees"),
        Word("WOODS", "nature", "a small forest"),
        Word("GROVE", "nature", "cluster of trees"),
        Word("ORCHARD", "nature", "planted fruit trees"),
        Word("TUNDRA", "nature", "cold treeless plain"),
        Word("GLACIER", "nature", "slow river of ice"),
        Word("ICEBERG", "nature", "floating frozen mountain"),
        Word("VOLCANO", "nature", "fire mountain"),
        Word("CRATER", "nature", "bowl left by impact"),
        Word("GEYSER", "nature", "bursting hot spring"),
        Word("WATERFALL", "nature", "river dropping off"),
        Word("RAPIDS", "nature", "fast rocky water"),
        Word("REEF", "nature", "underwater coral wall"),
        Word("LAGOON", "nature", "shallow separated water"),
        Word("DELTA", "nature", "river's mouth fan"),
        Word("ESTUARY", "nature", "where river meets sea"),
        Word("MEADOWLARK", "creature", "field singing bird"),
        Word("CAVERN", "shelter", "a natural underground room"),
        Word("CAVE", "shelter", "stone hollow"),
        Word("GROTTO", "shelter", "small pretty cave"),
        Word("MOUND", "nature", "a small heap of earth"),

        // ---- weather / seasons / sky ----
        Word("STORM", "weather", "wind, rain, and thunder"),
        Word("THUNDER", "weather", "the crack after lightning"),
        Word("LIGHTNING", "weather", "sky-bolt of light"),
        Word("FROST", "weather", "a thin coat of ice"),
        Word("SNOW", "weather", "cold white flakes"),
        Word("HAIL", "weather", "ice balls from the sky"),
        Word("SLEET", "weather", "half-frozen rain"),
        Word("RAIN", "weather", "water from the clouds"),
        Word("DRIZZLE", "weather", "light steady rain"),
        Word("MIST", "weather", "fine hanging droplets"),
        Word("FOG", "weather", "thick low cloud"),
        Word("DEW", "weather", "morning drops on grass"),
        Word("BREEZE", "weather", "gentle wind"),
        Word("GALE", "weather", "very strong wind"),
        Word("HURRICANE", "weather", "spinning tropical storm"),
        Word("TORNADO", "weather", "a spinning column of wind"),
        Word("BLIZZARD", "weather", "wind-driven snow"),
        Word("CYCLONE", "weather", "big spinning storm"),
        Word("DROUGHT", "weather", "long time without rain"),
        Word("HEATWAVE", "weather", "burning stretch of days"),
        Word("MONSOON", "weather", "the seasonal rains"),
        Word("SPRING", "season", "when green returns"),
        Word("SUMMER", "season", "hot long days"),
        Word("AUTUMN", "season", "when leaves turn and fall"),
        Word("WINTER", "season", "cold, short days"),
        Word("HARVEST", "season", "when the crops are gathered"),
        Word("DAWN", "time", "the day's first light"),
        Word("MORNING", "time", "before noon"),
        Word("NOON", "time", "the middle of the day"),
        Word("AFTERNOON", "time", "after noon, before dusk"),
        Word("EVENING", "time", "day's slow end"),
        Word("TWILIGHT", "time", "the dim between"),
        Word("SUNSET", "time", "the sun going down"),
        Word("SUNRISE", "time", "the sun coming up"),
        Word("NIGHT", "time", "the dark hours"),
        Word("MOON", "sky", "the earth's cold companion"),
        Word("SUN", "sky", "the sky's great fire"),
        Word("STAR", "sky", "a night's twinkle"),
        Word("COMET", "sky", "streaking icy visitor"),
        Word("METEOR", "sky", "a shooting light"),
        Word("PLANET", "sky", "a body around the sun"),
        Word("GALAXY", "sky", "a great swirl of stars"),
        Word("NEBULA", "sky", "a cloud between stars"),
        Word("CLOUD", "sky", "floating water in the air"),
        Word("SKY", "sky", "what stretches above"),
        Word("HORIZON", "sky", "where sky meets earth"),
        Word("RAINBOW", "weather", "sunlight through rain"),
        Word("AURORA", "sky", "the polar light show"),

        // ---- fire, light, elements ----
        Word("FIRE", "fire", "flame that eats wood"),
        Word("FLAME", "fire", "the fire's dancing edge"),
        Word("SPARK", "fire", "a bit of fire jumping"),
        Word("EMBER", "fire", "the last glow of a coal"),
        Word("BLAZE", "fire", "a bright fierce flame"),
        Word("SMOKE", "fire", "what rises from a burning log"),
        Word("ASH", "fire", "what fire leaves behind"),
        Word("COAL", "fire", "black burning rock"),
        Word("TORCH", "fire", "a stick of fire"),
        Word("CANDLE", "fire", "wax-and-wick light"),
        Word("LANTERN", "light", "a portable lamp"),
        Word("LAMP", "light", "an indoor light"),
        Word("BEACON", "light", "signal fire for far seeing"),
        Word("BONFIRE", "fire", "big outdoor fire"),
        Word("ICE", "element", "frozen water"),
        Word("WATER", "element", "H2O"),
        Word("EARTH", "element", "soil and stone"),
        Word("AIR", "element", "what we breathe"),
        Word("METAL", "material", "hard shiny substance"),
        Word("STONE", "material", "the earth's hard piece"),
        Word("ROCK", "material", "a stone bigger"),
        Word("SAND", "material", "worn-down rock grains"),
        Word("GLASS", "material", "a clear brittle sheet"),
        Word("WOOD", "material", "the tree's flesh"),
        Word("PAPER", "material", "thin flat writing surface"),
        Word("CLOTH", "material", "woven fabric"),
        Word("SILVER", "material", "shining precious metal"),
        Word("GOLD", "material", "the yellow prized metal"),
        Word("COPPER", "material", "reddish metal"),
        Word("IRON", "material", "strong grey metal"),
        Word("STEEL", "material", "the harder alloy"),
        Word("BRONZE", "material", "copper and tin blend"),
        Word("MARBLE", "material", "polished stone of sculpture"),
        Word("GRANITE", "material", "hard speckled stone"),
        Word("CRYSTAL", "material", "clear ordered mineral"),
        Word("DIAMOND", "material", "the hardest gem"),
        Word("RUBY", "material", "red precious stone"),
        Word("EMERALD", "material", "green precious stone"),
        Word("SAPPHIRE", "material", "blue precious stone"),
        Word("PEARL", "material", "the oyster's white gem"),
        Word("JADE", "material", "green carved stone"),
        Word("AMBER", "material", "fossilized golden resin"),

        // ---- plants / flowers / trees ----
        Word("TREE", "plant", "wood-trunked tall grower"),
        Word("OAK", "plant", "a mighty acorn-tree"),
        Word("PINE", "plant", "needle-leaved evergreen"),
        Word("MAPLE", "plant", "syrup-giving tree"),
        Word("BIRCH", "plant", "paper-barked slender tree"),
        Word("WILLOW", "plant", "the weeping tree"),
        Word("CEDAR", "plant", "fragrant evergreen wood"),
        Word("REDWOOD", "plant", "coastal giant tree"),
        Word("BAMBOO", "plant", "the hollow tall grass"),
        Word("PALM", "plant", "tropical fronded tree"),
        Word("FERN", "plant", "the leafy shade lover"),
        Word("MOSS", "plant", "soft green rock cover"),
        Word("VINE", "plant", "the climbing creeper"),
        Word("IVY", "plant", "wall climber with leaves"),
        Word("GRASS", "plant", "the lawn's green blade"),
        Word("REED", "plant", "wet-loving tall grass"),
        Word("BUSH", "plant", "small stemmy plant"),
        Word("SHRUB", "plant", "another word for bush"),
        Word("HEDGE", "plant", "planted border of shrubs"),
        Word("THORN", "plant", "a sharp point on a stem"),
        Word("CACTUS", "plant", "desert spike"),
        Word("ROSE", "flower", "the thorned red bloom"),
        Word("LILY", "flower", "trumpet-shaped white bloom"),
        Word("TULIP", "flower", "cup-shaped spring flower"),
        Word("DAISY", "flower", "white-petal yellow-center"),
        Word("VIOLET", "flower", "a small purple bloom"),
        Word("ORCHID", "flower", "exotic patterned bloom"),
        Word("IRIS", "flower", "the sword-leaf flower"),
        Word("POPPY", "flower", "red field flower"),
        Word("SUNFLOWER", "flower", "yellow face that follows the sun"),
        Word("JASMINE", "flower", "small perfumed white bloom"),
        Word("LOTUS", "flower", "floats on the pond"),
        Word("PETAL", "plant", "colored leaf of a flower"),
        Word("BLOSSOM", "plant", "flowering of a fruit tree"),
        Word("BUD", "plant", "flower before it opens"),
        Word("BLOOM", "plant", "the flower fully open"),
        Word("LEAF", "plant", "the flat green solar panel"),
        Word("BRANCH", "plant", "a tree's arm"),
        Word("TRUNK", "plant", "the tree's stout body"),
        Word("ROOT", "plant", "the tree's underground grip"),
        Word("BARK", "plant", "the tree's rough coat"),
        Word("SEED", "plant", "the beginning of a plant"),
        Word("FRUIT", "plant", "seed-bearing sweet reward"),
        Word("GARDEN", "place", "planted patch of earth"),

        // ---- fruits ----
        Word("APPLE", "fruit", "red or green orchard fruit"),
        Word("BANANA", "fruit", "yellow curved tropical"),
        Word("ORANGE", "fruit", "juicy citrus round"),
        Word("LEMON", "fruit", "sharp yellow citrus"),
        Word("LIME", "fruit", "small green citrus"),
        Word("GRAPE", "fruit", "wine's small round"),
        Word("CHERRY", "fruit", "small red stone-fruit"),
        Word("PEACH", "fruit", "fuzzy summer fruit"),
        Word("PEAR", "fruit", "bell-shaped orchard fruit"),
        Word("PLUM", "fruit", "purple round stone-fruit"),
        Word("MANGO", "fruit", "the tropical king"),
        Word("PAPAYA", "fruit", "orange tropical melon"),
        Word("PINEAPPLE", "fruit", "spiky sweet tropical"),
        Word("COCONUT", "fruit", "hard shell with sweet water"),
        Word("STRAWBERRY", "fruit", "red seeded on the outside"),
        Word("BLUEBERRY", "fruit", "small blue bush berry"),
        Word("RASPBERRY", "fruit", "red bumpy berry"),
        Word("BLACKBERRY", "fruit", "dark thorny berry"),
        Word("MELON", "fruit", "big juicy summer fruit"),
        Word("WATERMELON", "fruit", "the picnic slice"),
        Word("KIWI", "fruit", "fuzzy brown, green inside"),
        Word("GUAVA", "fruit", "tropical sweet-tart fruit"),
        Word("FIG", "fruit", "seedy sweet dried snack"),
        Word("DATE", "fruit", "sweet palm fruit"),
        Word("APRICOT", "fruit", "small orange stone-fruit"),
        Word("POMEGRANATE", "fruit", "many-seeded ruby fruit"),
        Word("AVOCADO", "fruit", "green creamy pit-fruit"),

        // ---- vegetables ----
        Word("CARROT", "vegetable", "orange root snack"),
        Word("POTATO", "vegetable", "the buried starch"),
        Word("TOMATO", "vegetable", "red vine fruit-veggie"),
        Word("ONION", "vegetable", "layered tear-maker"),
        Word("GARLIC", "vegetable", "pungent flavor bulb"),
        Word("PEPPER", "vegetable", "crisp bell or fiery chili"),
        Word("LETTUCE", "vegetable", "leafy salad green"),
        Word("CABBAGE", "vegetable", "leafy round head"),
        Word("BROCCOLI", "vegetable", "green tree florets"),
        Word("CAULIFLOWER", "vegetable", "white flowered head"),
        Word("SPINACH", "vegetable", "iron-rich dark greens"),
        Word("CUCUMBER", "vegetable", "long green cool salad"),
        Word("ZUCCHINI", "vegetable", "long green summer squash"),
        Word("PUMPKIN", "vegetable", "orange autumn gourd"),
        Word("SQUASH", "vegetable", "a hard-skinned gourd"),
        Word("CORN", "vegetable", "yellow-kerneled cob"),
        Word("BEANS", "vegetable", "pods full of protein"),
        Word("PEAS", "vegetable", "little green pods"),
        Word("RADISH", "vegetable", "sharp pink-red root"),
        Word("BEET", "vegetable", "the dark red root"),
        Word("TURNIP", "vegetable", "white and purple root"),
        Word("CELERY", "vegetable", "crunchy green stalk"),
        Word("ASPARAGUS", "vegetable", "spring green spear"),
        Word("EGGPLANT", "vegetable", "shiny purple oval"),
        Word("MUSHROOM", "vegetable", "the earthy fungus"),
        Word("ARTICHOKE", "vegetable", "layered green globe"),
        Word("KALE", "vegetable", "curly dark leafy green"),
        Word("CHARD", "vegetable", "colorful stem greens"),

        // ---- food, meals, cooking ----
        Word("BREAD", "food", "the baked loaf staple"),
        Word("BUTTER", "food", "creamy spread for toast"),
        Word("CHEESE", "food", "aged milk delight"),
        Word("MILK", "food", "white breakfast drink"),
        Word("YOGURT", "food", "cultured tangy dairy"),
        Word("CREAM", "food", "thickened milk top"),
        Word("EGG", "food", "the shelled protein"),
        Word("BACON", "food", "smoked pork strips"),
        Word("HAM", "food", "cured pork slice"),
        Word("SAUSAGE", "food", "stuffed meat tube"),
        Word("STEAK", "food", "a thick cut of meat"),
        Word("CHOP", "food", "small cut of meat"),
        Word("ROAST", "food", "meat baked whole"),
        Word("SOUP", "food", "liquid meal in a bowl"),
        Word("STEW", "food", "chunks in a thick broth"),
        Word("SALAD", "food", "cold mixed greens"),
        Word("PASTA", "food", "the boiled Italian staple"),
        Word("PIZZA", "food", "cheesy round Italian"),
        Word("BURGER", "food", "patty in a bun"),
        Word("FRIES", "food", "crispy potato sticks"),
        Word("CHIPS", "food", "salty thin crunch"),
        Word("RICE", "food", "small grain staple"),
        Word("NOODLES", "food", "long boiled ribbons"),
        Word("CURRY", "food", "spiced stew of many places"),
        Word("SUSHI", "food", "raw fish and rice"),
        Word("TACO", "food", "folded shell with fillings"),
        Word("PANCAKE", "food", "flat breakfast round"),
        Word("WAFFLE", "food", "grid-patterned breakfast"),
        Word("MUFFIN", "food", "sweet baked cup"),
        Word("BAGEL", "food", "boiled-then-baked ring"),
        Word("DONUT", "food", "sweet fried ring"),
        Word("CAKE", "food", "the birthday sponge"),
        Word("PIE", "food", "sweet or savoury filled crust"),
        Word("COOKIE", "food", "sweet crumbly snack"),
        Word("BROWNIE", "food", "chocolate baked square"),
        Word("PUDDING", "food", "creamy sweet dessert"),
        Word("CANDY", "food", "sugary sweet treat"),
        Word("CHOCOLATE", "food", "cocoa-based bliss"),
        Word("CARAMEL", "food", "burnt-sugar sweet"),
        Word("HONEY", "food", "the bee's golden gift"),
        Word("SYRUP", "food", "sticky sweet pour"),
        Word("JAM", "food", "fruit spread on toast"),
        Word("SUGAR", "food", "the sweet crystal"),
        Word("SALT", "food", "the savory crystal"),
        Word("SPICE", "food", "flavor from far away"),
        Word("HERB", "food", "leafy flavor booster"),
        Word("MINT", "food", "cool leafy flavor"),
        Word("BASIL", "food", "Italian green herb"),
        Word("CILANTRO", "food", "polarizing green herb"),
        Word("PARSLEY", "food", "curly plate garnish"),
        Word("GINGER", "food", "spicy root of tea and cake"),
        Word("TURMERIC", "food", "yellow curry spice"),
        Word("CUMIN", "food", "warm brown spice seed"),

        // ---- drinks ----
        Word("WATER", "drink", "clear thirst quencher"),
        Word("COFFEE", "drink", "the morning wake-up"),
        Word("TEA", "drink", "steeped leaves"),
        Word("JUICE", "drink", "squeezed fruit liquid"),
        Word("SODA", "drink", "bubbly sweet fizz"),
        Word("COCOA", "drink", "hot chocolate cup"),
        Word("SMOOTHIE", "drink", "blended fruity drink"),
        Word("LEMONADE", "drink", "sweet-sour summer"),
        Word("WINE", "drink", "fermented grape"),
        Word("BEER", "drink", "brewed and hopped"),
        Word("CIDER", "drink", "fermented apple"),
        Word("WHISKEY", "drink", "aged grain spirit"),
        Word("VODKA", "drink", "clear grain spirit"),
        Word("RUM", "drink", "sugarcane spirit"),
        Word("GIN", "drink", "juniper spirit"),
        Word("BRANDY", "drink", "distilled wine"),

        // ---- objects, tools, household ----
        Word("CHAIR", "object", "a seat with four legs"),
        Word("TABLE", "object", "flat top on legs"),
        Word("BED", "object", "sleeper's soft frame"),
        Word("DESK", "object", "the study table"),
        Word("SHELF", "object", "stack for books"),
        Word("DRAWER", "object", "the pull-out box"),
        Word("CABINET", "object", "storage on the wall"),
        Word("WARDROBE", "object", "the clothes cabinet"),
        Word("MIRROR", "object", "reflects your face"),
        Word("CLOCK", "object", "shows the hour"),
        Word("WATCH", "object", "the wrist timekeeper"),
        Word("CALENDAR", "object", "the days in a grid"),
        Word("BOOK", "object", "pages bound to spine"),
        Word("NOTEBOOK", "object", "blank writing pages"),
        Word("PEN", "object", "an ink-filled writer"),
        Word("PENCIL", "object", "wooden graphite writer"),
        Word("ERASER", "object", "removes pencil marks"),
        Word("PAPER", "object", "the thin white sheet"),
        Word("ENVELOPE", "object", "holds a letter"),
        Word("STAMP", "object", "sticks on mail"),
        Word("LETTER", "object", "written message sent"),
        Word("KEY", "object", "opens a lock"),
        Word("LOCK", "object", "keeps a door closed"),
        Word("DOOR", "object", "the room's mouth"),
        Word("WINDOW", "object", "the wall's eye"),
        Word("CURTAIN", "object", "covers a window"),
        Word("BLIND", "object", "slatted window cover"),
        Word("CARPET", "object", "the floor's soft cover"),
        Word("RUG", "object", "smaller floor mat"),
        Word("PILLOW", "object", "under the sleeper's head"),
        Word("BLANKET", "object", "warm cover on the bed"),
        Word("QUILT", "object", "patchwork blanket"),
        Word("SHEET", "object", "the bed's cotton layer"),
        Word("TOWEL", "object", "for drying off"),
        Word("SOAP", "object", "bubbles for cleaning"),
        Word("BRUSH", "object", "bristles on a handle"),
        Word("COMB", "object", "teeth for the hair"),
        Word("BROOM", "object", "sweeps the floor"),
        Word("MOP", "object", "washes the floor"),
        Word("BUCKET", "object", "the water carrier"),
        Word("PAN", "object", "for cooking on the stove"),
        Word("POT", "object", "deeper cooking vessel"),
        Word("KETTLE", "object", "whistles for tea"),
        Word("BOWL", "object", "round eating vessel"),
        Word("PLATE", "object", "flat eating dish"),
        Word("CUP", "object", "small drinking vessel"),
        Word("MUG", "object", "big handled cup"),
        Word("GLASS", "object", "clear drinking vessel"),
        Word("SPOON", "object", "the round scoop"),
        Word("FORK", "object", "the pointed picker"),
        Word("KNIFE", "object", "the cutting blade"),
        Word("PLATTER", "object", "large serving dish"),
        Word("TRAY", "object", "flat carrier for many dishes"),
        Word("NAPKIN", "object", "the lap protector"),
        Word("TABLECLOTH", "object", "the table's fabric cover"),
        Word("STOVE", "object", "cooks the food"),
        Word("OVEN", "object", "bakes the bread"),
        Word("FRIDGE", "object", "keeps food cold"),
        Word("FREEZER", "object", "keeps food frozen"),
        Word("MICROWAVE", "object", "quick heat box"),
        Word("SINK", "object", "for washing dishes"),
        Word("FAUCET", "object", "where the water comes out"),
        Word("SHOWER", "object", "a stand-up bath"),
        Word("BATHTUB", "object", "the soaking tub"),
        Word("TOILET", "object", "bathroom porcelain"),
        Word("RADIATOR", "object", "warms a room"),
        Word("FAN", "object", "the room's cool breeze"),
        Word("HEATER", "object", "makes the room warm"),

        // ---- tools & weapons ----
        Word("HAMMER", "tool", "drives a nail"),
        Word("SAW", "tool", "cuts through wood"),
        Word("DRILL", "tool", "makes a hole"),
        Word("SCREWDRIVER", "tool", "turns a screw"),
        Word("WRENCH", "tool", "turns a bolt"),
        Word("PLIERS", "tool", "gripping jaws"),
        Word("SHOVEL", "tool", "digs the earth"),
        Word("SPADE", "tool", "another digging blade"),
        Word("RAKE", "tool", "gathers leaves"),
        Word("HOE", "tool", "loosens soil"),
        Word("AXE", "tool", "chops wood"),
        Word("CHISEL", "tool", "carves the stone"),
        Word("PLANE", "tool", "smooths the wood"),
        Word("NAIL", "tool", "the metal spike"),
        Word("SCREW", "tool", "threaded fastener"),
        Word("BOLT", "tool", "big threaded fastener"),
        Word("SWORD", "weapon", "long blade of the knight"),
        Word("DAGGER", "weapon", "a short blade for close work"),
        Word("BLADE", "weapon", "the sharp edge of a sword"),
        Word("SPEAR", "weapon", "a long thrusting stick"),
        Word("LANCE", "weapon", "a long cavalry spear"),
        Word("BOW", "weapon", "shoots an arrow"),
        Word("ARROW", "weapon", "the bowman's shot"),
        Word("CROSSBOW", "weapon", "the mechanical bow"),
        Word("ARBALEST", "weapon", "a large medieval crossbow"),
        Word("MACE", "weapon", "spiked heavy club"),
        Word("CLUB", "weapon", "a heavy stick"),
        Word("HAMMER", "weapon", "the war smasher"),
        Word("AXE", "weapon", "the woodcutter's war tool"),
        Word("HALBERD", "weapon", "polearm with an axe head"),
        Word("SLING", "weapon", "cord for hurling stones"),
        Word("SHIELD", "armor", "the arm's protector"),
        Word("HELMET", "armor", "protects the head"),
        Word("ARMOR", "armor", "worn metal defense"),
        Word("GAUNTLET", "armor", "the metal glove"),
        Word("CUIRASS", "armor", "breastplate armor"),
        Word("VISOR", "armor", "the face guard"),
        Word("PISTOL", "weapon", "single-hand firearm"),
        Word("RIFLE", "weapon", "long-barrel firearm"),
        Word("SHOTGUN", "weapon", "spread-shot firearm"),
        Word("CANNON", "weapon", "the roaring big gun"),
        Word("BULLET", "weapon", "what the gun fires"),
        Word("BOMB", "weapon", "the exploder"),
        Word("MINE", "weapon", "buried surprise"),
        Word("GRENADE", "weapon", "hand-thrown boom"),

        // ---- clothing ----
        Word("SHIRT", "clothing", "torso top"),
        Word("BLOUSE", "clothing", "light dressy top"),
        Word("SWEATER", "clothing", "warm knit top"),
        Word("JACKET", "clothing", "a light coat"),
        Word("COAT", "clothing", "outer layer for cold"),
        Word("VEST", "clothing", "sleeveless torso layer"),
        Word("PANTS", "clothing", "the leg covers"),
        Word("TROUSERS", "clothing", "another name for pants"),
        Word("JEANS", "clothing", "denim pants"),
        Word("SHORTS", "clothing", "short pants for warm days"),
        Word("SKIRT", "clothing", "hangs from the waist"),
        Word("DRESS", "clothing", "a one-piece garment"),
        Word("GOWN", "clothing", "a long formal dress"),
        Word("SUIT", "clothing", "the matched jacket and pants"),
        Word("TIE", "clothing", "the collar knot"),
        Word("SCARF", "clothing", "wraps around the neck"),
        Word("GLOVES", "clothing", "for the hands"),
        Word("MITTENS", "clothing", "no-finger warm hand covers"),
        Word("SOCKS", "clothing", "cover the feet under shoes"),
        Word("BOOTS", "clothing", "the tall shoes"),
        Word("SANDALS", "clothing", "open summer shoes"),
        Word("SHOES", "clothing", "cover the feet"),
        Word("SNEAKERS", "clothing", "rubber-soled athletic"),
        Word("SLIPPERS", "clothing", "soft indoor foot covers"),
        Word("HAT", "clothing", "for the head"),
        Word("CAP", "clothing", "a hat with a peak"),
        Word("HELMET", "clothing", "a rider's head guard"),
        Word("BELT", "clothing", "holds the pants up"),
        Word("BUCKLE", "object", "the belt's clasp"),
        Word("BUTTON", "object", "shirt fastener"),
        Word("ZIPPER", "object", "the sliding closure"),
        Word("POCKET", "clothing", "small carry pouch"),
        Word("SLEEVE", "clothing", "the arm cover"),
        Word("COLLAR", "clothing", "the shirt's neck edge"),
        Word("HOOD", "clothing", "the head cover on a coat"),

        // ---- body / anatomy ----
        Word("HEAD", "body", "the top of the body"),
        Word("HAIR", "body", "grows from the scalp"),
        Word("BRAIN", "body", "the thinker"),
        Word("SKULL", "body", "the head's bone"),
        Word("FACE", "body", "the front of the head"),
        Word("EYE", "body", "the seeing organ"),
        Word("NOSE", "body", "the smeller"),
        Word("MOUTH", "body", "for eating and talking"),
        Word("LIP", "body", "edges of the mouth"),
        Word("TEETH", "body", "chew the food"),
        Word("TONGUE", "body", "tastes and talks"),
        Word("EAR", "body", "the hearer"),
        Word("CHEEK", "body", "the face's side"),
        Word("CHIN", "body", "under the mouth"),
        Word("JAW", "body", "the mouth's hinge"),
        Word("NECK", "body", "the head's stalk"),
        Word("SHOULDER", "body", "arm meets torso"),
        Word("ARM", "body", "the reacher"),
        Word("ELBOW", "body", "the arm's bend"),
        Word("WRIST", "body", "the hand's hinge"),
        Word("HAND", "body", "five-fingered grasper"),
        Word("FINGER", "body", "the pointer"),
        Word("THUMB", "body", "the opposing digit"),
        Word("NAIL", "body", "grows on the finger tip"),
        Word("PALM", "body", "the inside of the hand"),
        Word("CHEST", "body", "front of the torso"),
        Word("BACK", "body", "behind the torso"),
        Word("SPINE", "body", "the back's column"),
        Word("STOMACH", "body", "the gut's sac"),
        Word("HEART", "body", "the blood pump"),
        Word("LUNG", "body", "breathes the air"),
        Word("LIVER", "body", "the filter organ"),
        Word("KIDNEY", "body", "bean-shaped filter"),
        Word("HIP", "body", "the pelvis joint"),
        Word("WAIST", "body", "the middle line"),
        Word("LEG", "body", "the walker"),
        Word("KNEE", "body", "the leg's hinge"),
        Word("SHIN", "body", "the leg's front"),
        Word("CALF", "body", "the leg's rear muscle"),
        Word("ANKLE", "body", "the foot's hinge"),
        Word("FOOT", "body", "you stand on it"),
        Word("HEEL", "body", "back of the foot"),
        Word("TOE", "body", "little foot digit"),
        Word("SKIN", "body", "the outer cover"),
        Word("BONE", "body", "hard body scaffold"),
        Word("BLOOD", "body", "the red flow"),
        Word("MUSCLE", "body", "the movers"),

        // ---- buildings / rooms / places ----
        Word("HOUSE", "place", "family shelter"),
        Word("HOME", "place", "where the heart is"),
        Word("KITCHEN", "place", "where meals are made"),
        Word("BEDROOM", "place", "the sleeping room"),
        Word("BATHROOM", "place", "the washing room"),
        Word("LIVING", "place", "the sitting room"),
        Word("DINING", "place", "where the table is"),
        Word("GARAGE", "place", "car's indoor spot"),
        Word("ATTIC", "place", "the roof-level room"),
        Word("BASEMENT", "place", "the underground floor"),
        Word("CELLAR", "place", "wine's underground home"),
        Word("HALLWAY", "place", "the connecting corridor"),
        Word("PORCH", "place", "the front step covered"),
        Word("BALCONY", "place", "the outside high ledge"),
        Word("PATIO", "place", "the outdoor stone area"),
        Word("YARD", "place", "the fenced grass around"),
        Word("STAIRS", "place", "the up-down steps"),
        Word("APARTMENT", "place", "one home in many"),
        Word("STUDIO", "place", "one-room apartment"),
        Word("MANSION", "place", "the very big house"),
        Word("CASTLE", "place", "stone home of a king"),
        Word("PALACE", "place", "the royal residence"),
        Word("TOWER", "place", "tall stone stack"),
        Word("KEEP", "place", "the castle's core"),
        Word("FORTRESS", "place", "strong military place"),
        Word("BARN", "place", "the farm's big shed"),
        Word("STABLE", "place", "the horse's home"),
        Word("HUT", "place", "small basic shelter"),
        Word("CABIN", "place", "the wooden getaway"),
        Word("LODGE", "place", "guest sleeping house"),
        Word("INN", "place", "roadside sleep and food"),
        Word("HOTEL", "place", "traveler's paid rooms"),
        Word("MOTEL", "place", "the roadside sleep"),
        Word("HOSPITAL", "place", "where the sick heal"),
        Word("CLINIC", "place", "small medical office"),
        Word("PHARMACY", "place", "where medicine is sold"),
        Word("SCHOOL", "place", "where children learn"),
        Word("COLLEGE", "place", "higher-learning place"),
        Word("UNIVERSITY", "place", "the big school of degrees"),
        Word("LIBRARY", "place", "quiet home of books"),
        Word("MUSEUM", "place", "old things on display"),
        Word("GALLERY", "place", "paintings on the wall"),
        Word("THEATER", "place", "stage and audience"),
        Word("CINEMA", "place", "big movie screen"),
        Word("STADIUM", "place", "sports crowd bowl"),
        Word("ARENA", "place", "fight or performance ring"),
        Word("MARKET", "place", "where things are bought"),
        Word("BAZAAR", "place", "the sprawling market"),
        Word("SHOP", "place", "a small store"),
        Word("STORE", "place", "buys and sells goods"),
        Word("MALL", "place", "many stores together"),
        Word("BAKERY", "place", "the bread shop"),
        Word("BUTCHER", "place", "the meat shop"),
        Word("FLORIST", "place", "the flower shop"),
        Word("CAFE", "place", "the coffee shop"),
        Word("RESTAURANT", "place", "food served at a table"),
        Word("BAR", "place", "where drinks are poured"),
        Word("PUB", "place", "the neighborhood beer place"),
        Word("BANK", "place", "where money is kept"),
        Word("POST", "place", "where mail is sent"),
        Word("STATION", "place", "trains stop here"),
        Word("AIRPORT", "place", "where planes take off"),
        Word("PORT", "place", "where ships come in"),
        Word("DOCK", "place", "the ship's platform"),
        Word("PIER", "place", "walk out over water"),
        Word("BRIDGE", "place", "crosses over water"),
        Word("TUNNEL", "place", "underground passage"),
        Word("PARK", "place", "the town's green space"),
        Word("PLAYGROUND", "place", "children play here"),
        Word("PLAZA", "place", "open public square"),
        Word("SQUARE", "place", "the town's open middle"),
        Word("VILLAGE", "place", "a small settlement"),
        Word("TOWN", "place", "bigger than a village"),
        Word("CITY", "place", "the big settlement"),
        Word("COUNTRY", "place", "a whole nation"),
        Word("CONTINENT", "place", "one of earth's big landmasses"),
        Word("WORLD", "place", "the whole earth"),
        Word("PLANET", "place", "the whole world seen from space"),

        // ---- vehicles / transport ----
        Word("CAR", "vehicle", "four-wheel road runner"),
        Word("TRUCK", "vehicle", "cargo hauler"),
        Word("VAN", "vehicle", "boxier passenger carrier"),
        Word("BUS", "vehicle", "many-passenger road transport"),
        Word("TAXI", "vehicle", "pay for a ride"),
        Word("MOTORCYCLE", "vehicle", "two-wheeled engine"),
        Word("SCOOTER", "vehicle", "smaller two-wheel motor"),
        Word("BICYCLE", "vehicle", "two-wheel pedal"),
        Word("TRICYCLE", "vehicle", "three-wheeled kid's bike"),
        Word("SKATEBOARD", "vehicle", "four small wheels on a plank"),
        Word("SCOOTER", "vehicle", "kick along on two wheels"),
        Word("TRAIN", "vehicle", "cars on rails"),
        Word("SUBWAY", "vehicle", "underground train"),
        Word("TRAM", "vehicle", "street rail car"),
        Word("PLANE", "vehicle", "flies through air"),
        Word("AIRPLANE", "vehicle", "the winged flyer"),
        Word("JET", "vehicle", "fast fuel-powered plane"),
        Word("HELICOPTER", "vehicle", "spinning blade flyer"),
        Word("GLIDER", "vehicle", "plane without engine"),
        Word("BALLOON", "vehicle", "hot air lifted flight"),
        Word("BLIMP", "vehicle", "the airship"),
        Word("ROCKET", "vehicle", "fires into space"),
        Word("SHUTTLE", "vehicle", "back-and-forth spaceship"),
        Word("SHIP", "vehicle", "ocean traveller"),
        Word("BOAT", "vehicle", "small water vessel"),
        Word("YACHT", "vehicle", "a fancy pleasure boat"),
        Word("CANOE", "vehicle", "small paddled boat"),
        Word("KAYAK", "vehicle", "one-person paddle boat"),
        Word("RAFT", "vehicle", "floating logs"),
        Word("SUBMARINE", "vehicle", "the underwater ship"),
        Word("SAILBOAT", "vehicle", "wind-powered boat"),
        Word("FERRY", "vehicle", "carries cars across water"),

        // ---- music / instruments / sound ----
        Word("SONG", "music", "sung words with a tune"),
        Word("TUNE", "music", "the melody's line"),
        Word("MELODY", "music", "the singable part"),
        Word("HARMONY", "music", "voices in agreement"),
        Word("RHYTHM", "music", "the beat pattern"),
        Word("BEAT", "music", "the pulse of a song"),
        Word("CHORD", "music", "three notes together"),
        Word("NOTE", "music", "a single sound in a scale"),
        Word("SCALE", "music", "ordered set of notes"),
        Word("KEY", "music", "the song's home tone"),
        Word("BAND", "music", "musicians playing together"),
        Word("CHOIR", "music", "singers together"),
        Word("ORCHESTRA", "music", "many instruments together"),
        Word("SYMPHONY", "music", "big classical work"),
        Word("BALLAD", "music", "slow story song"),
        Word("ANTHEM", "music", "big rousing song"),
        Word("LULLABY", "music", "sleep song"),
        Word("HYMN", "music", "religious song"),
        Word("CHANT", "music", "repeated group cry"),
        Word("OPERA", "music", "sung stage story"),
        Word("PIANO", "instrument", "88 black-and-white keys"),
        Word("GUITAR", "instrument", "six strings and a neck"),
        Word("VIOLIN", "instrument", "the bowed high string"),
        Word("CELLO", "instrument", "the big bowed string"),
        Word("BASS", "instrument", "the deep string"),
        Word("HARP", "instrument", "many strings plucked"),
        Word("DRUM", "instrument", "the round hit skin"),
        Word("CYMBAL", "instrument", "the metal crash"),
        Word("FLUTE", "instrument", "the side-blown pipe"),
        Word("CLARINET", "instrument", "the reed black tube"),
        Word("SAXOPHONE", "instrument", "the shiny brass jazz horn"),
        Word("TRUMPET", "instrument", "the brass fanfare"),
        Word("TROMBONE", "instrument", "the sliding brass"),
        Word("TUBA", "instrument", "the deep brass"),
        Word("HORN", "instrument", "the coiled brass"),
        Word("BANJO", "instrument", "the round-body twang"),
        Word("UKULELE", "instrument", "the little four-string"),
        Word("HARMONICA", "instrument", "the pocket mouth organ"),
        Word("ACCORDION", "instrument", "the squeezebox"),
        Word("ORGAN", "instrument", "the pipe keyboard"),
        Word("BELL", "instrument", "rung by a rope"),
        Word("WHISTLE", "instrument", "sharp small tune"),

        // ---- sound / voice ----
        Word("VOICE", "sound", "the mouth's tool"),
        Word("SHOUT", "sound", "loud angry cry"),
        Word("SCREAM", "sound", "highest fear cry"),
        Word("YELL", "sound", "loud call"),
        Word("SIGH", "sound", "breath of tiredness"),
        Word("MURMUR", "sound", "low soft speech"),
        Word("GIGGLE", "sound", "quick light laugh"),
        Word("LAUGH", "sound", "sound of joy"),
        Word("CHUCKLE", "sound", "quiet contented laugh"),
        Word("CRY", "sound", "sound of tears"),
        Word("SOB", "sound", "the shaky cry"),
        Word("WEEP", "sound", "quiet tearful cry"),
        Word("MOAN", "sound", "long low sound of pain"),
        Word("GROAN", "sound", "the tired complaint"),
        Word("HISS", "sound", "the serpent's sound"),
        Word("ROAR", "sound", "the lion's shout"),
        Word("BARK", "sound", "the dog's speech"),
        Word("MEOW", "sound", "the cat's speech"),
        Word("MOO", "sound", "the cow's speech"),
        Word("OINK", "sound", "the pig's speech"),
        Word("QUACK", "sound", "the duck's speech"),
        Word("CHIRP", "sound", "the small bird's speech"),
        Word("BUZZ", "sound", "the bee's speech"),
        Word("CLICK", "sound", "small hard tap"),
        Word("BEEP", "sound", "the machine's short note"),
        Word("SNORE", "sound", "the sleeper's growl"),
        Word("KNOCK", "sound", "at the door"),
        Word("SPLASH", "sound", "of water hit"),
        Word("CRASH", "sound", "of something breaking"),
        Word("BOOM", "sound", "of a great blast"),
        Word("BANG", "sound", "of a slam"),
        Word("PATTER", "sound", "rain on a roof"),

        // ---- emotions & mind ----
        Word("HAPPY", "emotion", "the smile inside"),
        Word("SAD", "emotion", "the tear inside"),
        Word("ANGRY", "emotion", "the fire inside"),
        Word("SCARED", "emotion", "the shrinking inside"),
        Word("BRAVE", "emotion", "the standing tall"),
        Word("PROUD", "emotion", "the puffed chest"),
        Word("SHY", "emotion", "the quiet corner"),
        Word("BORED", "emotion", "the slow yawn"),
        Word("EXCITED", "emotion", "the buzzing joy"),
        Word("CALM", "emotion", "the still lake"),
        Word("ANXIOUS", "emotion", "the tight chest"),
        Word("NERVOUS", "emotion", "the shaky hands"),
        Word("LONELY", "emotion", "the empty room"),
        Word("HOPE", "emotion", "the small light ahead"),
        Word("DESPAIR", "emotion", "no light at all"),
        Word("PRIDE", "emotion", "the earned high head"),
        Word("SHAME", "emotion", "the lowered head"),
        Word("GUILT", "emotion", "knowing you did wrong"),
        Word("REGRET", "emotion", "wishing you had not"),
        Word("ENVY", "emotion", "wanting what they have"),
        Word("JEALOUSY", "emotion", "protecting what is yours"),
        Word("LOVE", "emotion", "the largest warmth"),
        Word("HATE", "emotion", "the cold rejection"),
        Word("LIKE", "emotion", "the warm nod"),
        Word("TRUST", "emotion", "believing in another"),
        Word("DOUBT", "emotion", "the unsure mind"),
        Word("PROMISE", "virtue", "given words to be kept"),
        Word("COURAGE", "virtue", "action despite fear"),
        Word("HONOR", "virtue", "worth beyond gain"),
        Word("MERCY", "virtue", "sparing when you could strike"),
        Word("TRUTH", "virtue", "what stays real"),
        Word("KINDNESS", "virtue", "small warmths given"),
        Word("PATIENCE", "virtue", "waiting without anger"),
        Word("HONESTY", "virtue", "saying the true thing"),
        Word("LOYALTY", "virtue", "standing by the flag"),
        Word("HUMILITY", "virtue", "the low bow"),
        Word("GRATITUDE", "virtue", "the thanks felt"),
        Word("DREAM", "mind", "vision in sleep"),
        Word("MEMORY", "mind", "what the mind holds"),
        Word("VISION", "mind", "sight of what may come"),
        Word("THOUGHT", "mind", "a piece of thinking"),
        Word("IDEA", "mind", "the spark of a plan"),
        Word("PLAN", "mind", "steps to a goal"),
        Word("GOAL", "mind", "the target aimed for"),
        Word("WISH", "mind", "wanting quietly"),
        Word("BELIEF", "mind", "the mind's stand"),
        Word("FAITH", "mind", "trust without proof"),

        // ---- verbs / actions ----
        Word("RUN", "action", "the fast leg move"),
        Word("WALK", "action", "the slow leg move"),
        Word("JUMP", "action", "up and off the ground"),
        Word("HOP", "action", "small jump"),
        Word("SKIP", "action", "the light step-hop"),
        Word("LEAP", "action", "the big jump"),
        Word("SPRINT", "action", "the fastest run"),
        Word("JOG", "action", "the slow steady run"),
        Word("CLIMB", "action", "go up with hands and feet"),
        Word("CRAWL", "action", "on hands and knees"),
        Word("SLIDE", "action", "smooth glide across"),
        Word("SLIP", "action", "the unwanted slide"),
        Word("FALL", "action", "to drop suddenly"),
        Word("STAND", "action", "to rise on the feet"),
        Word("SIT", "action", "to lower onto a seat"),
        Word("KNEEL", "action", "to lower onto the knees"),
        Word("BOW", "action", "bend at the waist"),
        Word("BEND", "action", "curve the body"),
        Word("STRETCH", "action", "reach out to lengthen"),
        Word("REACH", "action", "extend the arm"),
        Word("GRAB", "action", "quick grasp"),
        Word("GRASP", "action", "to firmly hold"),
        Word("HOLD", "action", "keep in the hand"),
        Word("CARRY", "action", "hold while moving"),
        Word("LIFT", "action", "raise into the air"),
        Word("DROP", "action", "release to fall"),
        Word("PUSH", "action", "press away"),
        Word("PULL", "action", "draw toward"),
        Word("THROW", "action", "let fly from the hand"),
        Word("CATCH", "action", "receive a throw"),
        Word("KICK", "action", "strike with the foot"),
        Word("PUNCH", "action", "hit with the fist"),
        Word("SLAP", "action", "open-hand strike"),
        Word("HUG", "action", "hold with both arms"),
        Word("KISS", "action", "touch with the lips"),
        Word("WAVE", "action", "the greeting hand"),
        Word("POINT", "action", "aim the finger"),
        Word("NOD", "action", "small head yes"),
        Word("SHAKE", "action", "quick side-to-side"),
        Word("SPEAK", "action", "make words out loud"),
        Word("TALK", "action", "everyday speaking"),
        Word("WRITE", "action", "put words on paper"),
        Word("READ", "action", "take words off the page"),
        Word("DRAW", "action", "make lines by hand"),
        Word("PAINT", "action", "put color on the surface"),
        Word("SING", "action", "make music with the voice"),
        Word("DANCE", "action", "move with the music"),
        Word("PLAY", "action", "have fun or perform"),
        Word("WORK", "action", "the labor of the day"),
        Word("REST", "action", "stop for a while"),
        Word("SLEEP", "action", "the night's rest"),
        Word("WAKE", "action", "leave the sleep"),
        Word("DREAM", "action", "the sleeper's story"),
        Word("EAT", "action", "put food in"),
        Word("DRINK", "action", "take liquid in"),
        Word("CHEW", "action", "grind between teeth"),
        Word("SWALLOW", "action", "the down-the-throat"),
        Word("BREATHE", "action", "the lung motion"),
        Word("BLINK", "action", "the eye's quick shut"),
        Word("STARE", "action", "long unbroken look"),
        Word("GLANCE", "action", "the quick look"),
        Word("SEARCH", "action", "look hard for"),
        Word("FIND", "action", "come upon what was hidden"),
        Word("LOSE", "action", "fail to keep"),
        Word("WIN", "action", "come out first"),
        Word("BUILD", "action", "put together"),
        Word("BREAK", "action", "come apart"),
        Word("FIX", "action", "make whole again"),
        Word("MAKE", "action", "bring into being"),
        Word("CREATE", "action", "bring the new"),
        Word("BAKE", "action", "cook in the oven"),
        Word("BOIL", "action", "heat water hot"),
        Word("FRY", "action", "cook in hot fat"),
        Word("ROAST", "action", "cook slow with dry heat"),
        Word("GRILL", "action", "cook over open flame"),
        Word("STEAM", "action", "cook over hot water"),
        Word("MIX", "action", "combine together"),
        Word("STIR", "action", "move round in a bowl"),
        Word("POUR", "action", "let liquid fall"),
        Word("SPILL", "action", "unwanted pour"),
        Word("WASH", "action", "clean with water"),
        Word("DRY", "action", "remove wetness"),
        Word("SWEEP", "action", "clear with a broom"),
        Word("PLANT", "action", "put seeds in the ground"),
        Word("GROW", "action", "become bigger over time"),
        Word("CUT", "action", "slice with a blade"),
        Word("CHOP", "action", "cut with sharp blows"),
        Word("SLICE", "action", "the flat clean cut"),
        Word("DIG", "action", "make a hole in the earth"),
        Word("BURY", "action", "put under the ground"),
        Word("HIDE", "action", "keep out of sight"),
        Word("SEEK", "action", "look for"),
        Word("FOLLOW", "action", "go behind"),
        Word("LEAD", "action", "go in front"),
        Word("TEACH", "action", "give knowledge"),
        Word("LEARN", "action", "receive knowledge"),
        Word("STUDY", "action", "focused learning"),
        Word("THINK", "action", "work the mind"),
        Word("REMEMBER", "action", "hold in the mind"),
        Word("FORGET", "action", "lose from the mind"),

        // ---- colors ----
        Word("RED", "color", "blood's shade"),
        Word("BLUE", "color", "the sky and the sea"),
        Word("YELLOW", "color", "the sun's shade"),
        Word("GREEN", "color", "the grass's shade"),
        Word("ORANGE", "color", "the fruit's shade"),
        Word("PURPLE", "color", "red and blue mixed"),
        Word("VIOLET", "color", "a paler purple"),
        Word("PINK", "color", "the pale red"),
        Word("BROWN", "color", "the earth's shade"),
        Word("BLACK", "color", "the night's shade"),
        Word("WHITE", "color", "the snow's shade"),
        Word("GREY", "color", "between black and white"),
        Word("SILVER", "color", "the shining grey"),
        Word("GOLDEN", "color", "the shining yellow"),
        Word("CRIMSON", "color", "deep rich red"),
        Word("SCARLET", "color", "bright vivid red"),
        Word("MAROON", "color", "brownish red"),
        Word("NAVY", "color", "the deep dark blue"),
        Word("TEAL", "color", "green-blue"),
        Word("TURQUOISE", "color", "bright green-blue"),
        Word("INDIGO", "color", "the deep purple-blue"),
        Word("BEIGE", "color", "the sandy pale"),
        Word("IVORY", "color", "the warm white"),

        // ---- occupations ----
        Word("DOCTOR", "job", "heals the sick"),
        Word("NURSE", "job", "the hospital carer"),
        Word("DENTIST", "job", "cleans the teeth"),
        Word("TEACHER", "job", "shows students how"),
        Word("PROFESSOR", "job", "the college teacher"),
        Word("STUDENT", "job", "the learner"),
        Word("LAWYER", "job", "argues the case"),
        Word("JUDGE", "job", "the courtroom decider"),
        Word("POLICE", "job", "keeps the peace"),
        Word("SOLDIER", "job", "the army's arm"),
        Word("SAILOR", "job", "the ship's crew"),
        Word("PILOT", "job", "flies the plane"),
        Word("DRIVER", "job", "handles the wheel"),
        Word("FARMER", "job", "grows the food"),
        Word("BAKER", "job", "makes the bread"),
        Word("BUTCHER", "job", "cuts the meat"),
        Word("COOK", "job", "makes the meals"),
        Word("CHEF", "job", "the head cook"),
        Word("WAITER", "job", "brings the food"),
        Word("BARBER", "job", "cuts the hair"),
        Word("TAILOR", "job", "makes the clothes"),
        Word("PAINTER", "job", "the brush artist"),
        Word("SCULPTOR", "job", "the stone-carver artist"),
        Word("WRITER", "job", "puts stories on paper"),
        Word("AUTHOR", "job", "the book's creator"),
        Word("POET", "job", "the writer of verse"),
        Word("SINGER", "job", "the vocal performer"),
        Word("ACTOR", "job", "plays a part"),
        Word("DANCER", "job", "the trained mover"),
        Word("MUSICIAN", "job", "plays an instrument"),
        Word("ARCHITECT", "job", "designs buildings"),
        Word("ENGINEER", "job", "designs the working thing"),
        Word("CARPENTER", "job", "the wood builder"),
        Word("PLUMBER", "job", "fixes the pipes"),
        Word("ELECTRICIAN", "job", "handles the wires"),
        Word("MECHANIC", "job", "fixes the car"),
        Word("SCIENTIST", "job", "asks questions of the world"),
        Word("BIOLOGIST", "job", "the life scientist"),
        Word("CHEMIST", "job", "the elements scientist"),
        Word("PHYSICIST", "job", "the matter scientist"),
        Word("ASTRONOMER", "job", "the stars scientist"),
        Word("ASTRONAUT", "job", "goes to space"),
        Word("EXPLORER", "job", "finds the new land"),
        Word("SPY", "job", "the secret watcher"),
        Word("DETECTIVE", "job", "solves the crime"),
        Word("REPORTER", "job", "tells the news"),
        Word("PHOTOGRAPHER", "job", "the picture-taker"),
        Word("MODEL", "job", "poses for a picture"),
        Word("BANKER", "job", "handles the money"),
        Word("MERCHANT", "job", "buys and sells"),
        Word("SHOPKEEPER", "job", "runs the small store"),
        Word("LIBRARIAN", "job", "watches the books"),
        Word("ATHLETE", "job", "the trained sports body"),
        Word("REFEREE", "job", "the fair caller"),
        Word("COACH", "job", "the trainer of players"),
        Word("KING", "title", "the crowned man"),
        Word("QUEEN", "title", "the crowned woman"),
        Word("PRINCE", "title", "the son of a king"),
        Word("PRINCESS", "title", "the daughter of a king"),
        Word("KNIGHT", "title", "sworn to a code"),
        Word("DUKE", "title", "high noble title"),
        Word("BARON", "title", "the small noble"),
        Word("LORD", "title", "the ruling name"),
        Word("MAYOR", "title", "the city's head"),
        Word("PRESIDENT", "title", "the country's chief"),
        Word("CAPTAIN", "title", "the ship's chief"),
        Word("GENERAL", "title", "the army's top"),
        Word("SERGEANT", "title", "the squad's chief"),

        // ---- sports & games ----
        Word("SPORT", "sport", "a physical game"),
        Word("GAME", "sport", "played for fun or a prize"),
        Word("MATCH", "sport", "one contest"),
        Word("TOURNAMENT", "sport", "many matches strung"),
        Word("CHAMPION", "sport", "the winner of all"),
        Word("TEAM", "sport", "a group of players"),
        Word("PLAYER", "sport", "one who plays"),
        Word("COACH", "sport", "the trainer"),
        Word("REFEREE", "sport", "the game's judge"),
        Word("SCORE", "sport", "the count of points"),
        Word("POINT", "sport", "one unit of score"),
        Word("GOAL", "sport", "the target for scoring"),
        Word("SOCCER", "sport", "kicked round ball"),
        Word("FOOTBALL", "sport", "the oval throw"),
        Word("BASKETBALL", "sport", "shot through a hoop"),
        Word("BASEBALL", "sport", "bat and diamond"),
        Word("CRICKET", "sport", "bat and wicket"),
        Word("TENNIS", "sport", "net and racquet"),
        Word("BADMINTON", "sport", "the light shuttle"),
        Word("VOLLEYBALL", "sport", "net over sand or court"),
        Word("HOCKEY", "sport", "stick and puck"),
        Word("RUGBY", "sport", "the tackling ball"),
        Word("GOLF", "sport", "hit small ball far"),
        Word("BOWLING", "sport", "knock down the pins"),
        Word("BOXING", "sport", "gloved fistfight"),
        Word("WRESTLING", "sport", "the grappling match"),
        Word("KARATE", "sport", "empty-hand martial art"),
        Word("JUDO", "sport", "the gentle way throw"),
        Word("TAEKWONDO", "sport", "the kicking art"),
        Word("FENCING", "sport", "the blade sport"),
        Word("ARCHERY", "sport", "the bow contest"),
        Word("SHOOTING", "sport", "the aiming sport"),
        Word("CYCLING", "sport", "riding a bicycle"),
        Word("RUNNING", "sport", "racing on foot"),
        Word("SKIING", "sport", "the snow slide sport"),
        Word("SNOWBOARDING", "sport", "the snow board"),
        Word("SKATING", "sport", "gliding on ice"),
        Word("HOCKEY", "sport", "puck on ice"),
        Word("SURFING", "sport", "riding a wave"),
        Word("SAILING", "sport", "wind-powered water"),
        Word("ROWING", "sport", "the oared boat race"),
        Word("FISHING", "sport", "sitting with a rod"),
        Word("HIKING", "sport", "a long walk"),
        Word("CAMPING", "sport", "sleeping outdoors"),
        Word("CLIMBING", "sport", "going up rocks"),
        Word("SWIMMING", "sport", "the water sport"),
        Word("DIVING", "sport", "head first into water"),
        Word("SKATEBOARDING", "sport", "the board and wheels"),
        Word("YOGA", "sport", "the stretching practice"),
        Word("CHESS", "game", "kings, queens, and knights on 64 squares"),
        Word("CHECKERS", "game", "the crowned red-and-black"),
        Word("POKER", "game", "the cards and bluff"),
        Word("BRIDGE", "game", "the bidding card game"),
        Word("DOMINOES", "game", "the tiled matching"),
        Word("SCRABBLE", "game", "the letter word grid"),
        Word("PUZZLE", "game", "pieces that fit"),
        Word("JIGSAW", "game", "picture pieces"),
        Word("CROSSWORD", "game", "words in a grid"),
        Word("SUDOKU", "game", "the number grid"),
        Word("MARBLE", "game", "small glass ball"),
        Word("KITE", "object", "flown on a string"),

        // ---- numbers / measures ----
        Word("ONE", "number", "the single"),
        Word("TWO", "number", "the pair"),
        Word("THREE", "number", "the trio"),
        Word("FOUR", "number", "a quartet"),
        Word("FIVE", "number", "a hand's count"),
        Word("SIX", "number", "half a dozen"),
        Word("SEVEN", "number", "the lucky one"),
        Word("EIGHT", "number", "the octet"),
        Word("NINE", "number", "one shy of ten"),
        Word("TEN", "number", "two hands"),
        Word("DOZEN", "number", "twelve of them"),
        Word("HUNDRED", "number", "a full century"),
        Word("THOUSAND", "number", "ten hundred"),
        Word("MILLION", "number", "a thousand thousand"),
        Word("INCH", "measure", "small length"),
        Word("FOOT", "measure", "twelve inches"),
        Word("YARD", "measure", "three feet"),
        Word("MILE", "measure", "long road distance"),
        Word("METER", "measure", "the metric length"),
        Word("KILOMETER", "measure", "a thousand meters"),
        Word("GRAM", "measure", "small weight"),
        Word("KILOGRAM", "measure", "a thousand grams"),
        Word("POUND", "measure", "sixteen ounces"),
        Word("OUNCE", "measure", "small weight of coffee"),
        Word("LITER", "measure", "metric volume"),
        Word("GALLON", "measure", "big volume"),
        Word("SECOND", "measure", "one tick of the clock"),
        Word("MINUTE", "measure", "sixty seconds"),
        Word("HOUR", "measure", "sixty minutes"),
        Word("DAY", "measure", "the sun's cycle"),
        Word("WEEK", "measure", "seven days"),
        Word("MONTH", "measure", "the calendar chunk"),
        Word("YEAR", "measure", "the earth's orbit"),
        Word("DECADE", "measure", "ten years"),
        Word("CENTURY", "measure", "a hundred years"),

        // ---- time / calendar ----
        Word("MONDAY", "day", "start of the work week"),
        Word("TUESDAY", "day", "the second"),
        Word("WEDNESDAY", "day", "the midweek"),
        Word("THURSDAY", "day", "the fourth"),
        Word("FRIDAY", "day", "start of the weekend"),
        Word("SATURDAY", "day", "the middle of the weekend"),
        Word("SUNDAY", "day", "the rest day"),
        Word("JANUARY", "month", "the year opens"),
        Word("FEBRUARY", "month", "the short one"),
        Word("MARCH", "month", "the spring begins"),
        Word("APRIL", "month", "the rain month"),
        Word("MAY", "month", "the flower month"),
        Word("JUNE", "month", "the wedding month"),
        Word("JULY", "month", "midsummer"),
        Word("AUGUST", "month", "hottest month"),
        Word("SEPTEMBER", "month", "the school month"),
        Word("OCTOBER", "month", "the pumpkin month"),
        Word("NOVEMBER", "month", "the thankful month"),
        Word("DECEMBER", "month", "the year closes"),
        Word("HOLIDAY", "time", "a day off"),
        Word("BIRTHDAY", "time", "your yearly cake day"),
        Word("WEDDING", "time", "when two are wed"),
        Word("FESTIVAL", "time", "a big shared celebration"),
        Word("CARNIVAL", "time", "the rolling celebration"),

        // ---- fantasy / mystical / dark theme extras ----
        Word("ELF", "creature", "the pointed-ear one"),
        Word("DWARF", "creature", "the mountain shortfolk"),
        Word("GNOME", "creature", "the tiny gardener"),
        Word("FAIRY", "creature", "small winged spirit"),
        Word("GOBLIN", "creature", "the mean green one"),
        Word("TROLL", "creature", "the stone bridge lurker"),
        Word("OGRE", "creature", "the huge dumb brute"),
        Word("GIANT", "creature", "the very large one"),
        Word("CENTAUR", "creature", "half man, half horse"),
        Word("UNICORN", "creature", "one-horned white horse"),
        Word("PEGASUS", "creature", "the winged horse"),
        Word("MERMAID", "creature", "half woman, half fish"),
        Word("SIREN", "creature", "the singing danger"),
        Word("VAMPIRE", "creature", "the blood drinker"),
        Word("WEREWOLF", "creature", "the moon-changer"),
        Word("ZOMBIE", "creature", "the walking dead"),
        Word("MUMMY", "creature", "the wrapped dead"),
        Word("GHOUL", "creature", "the grave feeder"),
        Word("BANSHEE", "creature", "the death-crying spirit"),
        Word("KNIGHT", "role", "the honor-bound warrior"),
        Word("PALADIN", "role", "the holy warrior"),
        Word("WARRIOR", "role", "the sworn fighter"),
        Word("RANGER", "role", "the wild scout"),
        Word("ROGUE", "role", "the shadow blade"),
        Word("MAGE", "role", "the caster of spells"),
        Word("SORCERER", "role", "born to raw magic"),
        Word("NECROMANCER", "role", "the dead-caller"),
        Word("PRIEST", "role", "the temple servant"),
        Word("DRUID", "role", "the nature caster"),
        Word("BARD", "role", "the singing traveler"),
        Word("ASSASSIN", "role", "the paid killer"),
        Word("THIEF", "role", "the taker in secret"),
        Word("GUARD", "role", "the standing watcher"),
        Word("QUEST", "story", "a long journey with a goal"),
        Word("LEGEND", "story", "a tale that grows with time"),
        Word("MYTH", "story", "the origin tale"),
        Word("FABLE", "story", "the beast-lesson tale"),
        Word("SAGA", "story", "the long many-part tale"),
        Word("EPIC", "story", "the grand poem-tale"),
        Word("PROPHECY", "story", "the fated future told"),
        Word("SCROLL", "object", "the rolled written page"),
        Word("TOME", "object", "a heavy old book"),
        Word("CROWN", "object", "worn by the king"),
        Word("THRONE", "object", "the king's seat"),
        Word("SCEPTER", "object", "the ceremonial staff"),
        Word("ORB", "object", "the round ceremonial"),
        Word("GRIMOIRE", "object", "the book of spells"),
        Word("AMULET", "object", "the protective charm"),
        Word("TALISMAN", "object", "the luck-bringing token"),
        Word("MEDALLION", "object", "the round hanging emblem"),
        Word("CHALICE", "object", "the ceremonial cup"),
        Word("GOBLET", "object", "the fancy drink cup"),
        Word("SHRINE", "place", "the small holy place"),
        Word("TEMPLE", "place", "the holy building"),
        Word("CHAPEL", "place", "the small holy room"),
        Word("CHURCH", "place", "the christian holy house"),
        Word("MOSQUE", "place", "the muslim holy house"),
        Word("PAGODA", "place", "the tiered Asian temple"),
        Word("SANCTUARY", "place", "the safe holy space"),
        Word("MONASTERY", "place", "the monks' home"),
        Word("ABBEY", "place", "the old religious house"),

        // ---- misc common ----
        Word("MONEY", "misc", "buys and pays"),
        Word("COIN", "misc", "the small round money"),
        Word("BILL", "misc", "the paper money"),
        Word("WALLET", "misc", "holds the money"),
        Word("PURSE", "misc", "the small money bag"),
        Word("BAG", "misc", "the flexible carry"),
        Word("SACK", "misc", "the coarse carry bag"),
        Word("BOX", "misc", "the square carry"),
        Word("CRATE", "misc", "the wooden shipping box"),
        Word("BARREL", "misc", "the round staved container"),
        Word("BASKET", "misc", "the woven carrier"),
        Word("BOTTLE", "misc", "narrow-neck container"),
        Word("JAR", "misc", "the wide-mouth container"),
        Word("CAN", "misc", "metal food container"),
        Word("TIN", "misc", "the small metal can"),
        Word("PACKAGE", "misc", "wrapped for delivery"),
        Word("PARCEL", "misc", "another delivery bundle"),
        Word("BOOK", "misc", "the reader's pages"),
        Word("MAGAZINE", "misc", "the glossy periodical"),
        Word("NEWSPAPER", "misc", "the daily news pages"),
        Word("MOVIE", "misc", "the film you watch"),
        Word("FILM", "misc", "cinema story"),
        Word("SHOW", "misc", "the tv program"),
        Word("SERIES", "misc", "many episodes"),
        Word("EPISODE", "misc", "one show installment"),
        Word("CHAPTER", "misc", "one book section"),
        Word("STORY", "misc", "a tale told"),
        Word("TALE", "misc", "another word for story"),
        Word("PLOT", "misc", "the story's shape"),
        Word("MYSTERY", "misc", "the story of the question"),
        Word("PICTURE", "misc", "the still image"),
        Word("PHOTO", "misc", "the camera image"),
        Word("PAINTING", "misc", "the artist's picture"),
        Word("DRAWING", "misc", "the pencil picture"),
        Word("SKETCH", "misc", "the quick drawing"),
        Word("STATUE", "misc", "the standing sculpture"),
        Word("SCULPTURE", "misc", "the carved figure"),
        Word("MUSIC", "misc", "organized sound"),
        Word("VOICE", "misc", "sound of the person"),
        Word("SILENCE", "misc", "no sound at all"),
        Word("NOISE", "misc", "unwanted sound"),
        Word("LIGHT", "misc", "the visible energy"),
        Word("DARK", "misc", "the absence of light"),
        Word("SHADE", "misc", "the softened light"),
        Word("SHINE", "misc", "the bright surface"),
        Word("GLOW", "misc", "the soft even light"),
        Word("GLEAM", "misc", "a brief shine"),
        Word("FLASH", "misc", "the sudden bright"),
        Word("SPARKLE", "misc", "the small bright twinkle"),
        Word("REFLECTION", "misc", "the mirror-back"),
        Word("SHADOW", "misc", "the light-blocked shape"),
        Word("SILHOUETTE", "misc", "the dark outline"),
        Word("FIGURE", "misc", "the shape of a person"),
        Word("FORM", "misc", "the outer shape"),
        Word("SHAPE", "misc", "the general form"),
        Word("SIZE", "misc", "how big"),
        Word("HEIGHT", "misc", "the up measure"),
        Word("WIDTH", "misc", "the side measure"),
        Word("DEPTH", "misc", "the down measure"),
        Word("LENGTH", "misc", "the long measure"),
        Word("WEIGHT", "misc", "how heavy"),
        Word("SPEED", "misc", "how fast"),
        Word("QUIET", "misc", "the low sound"),
        Word("LOUD", "misc", "the high sound"),
        Word("BRIGHT", "misc", "full of light"),
        Word("DIM", "misc", "low in light"),
        Word("BIG", "misc", "large in size"),
        Word("SMALL", "misc", "little in size"),
        Word("LARGE", "misc", "of great size"),
        Word("TINY", "misc", "very small"),
        Word("HUGE", "misc", "very large"),
        Word("SHORT", "misc", "not tall or long"),
        Word("TALL", "misc", "high in size"),
        Word("FAT", "misc", "wide in body"),
        Word("THIN", "misc", "narrow in body"),
        Word("HEAVY", "misc", "hard to lift"),
        Word("LIGHT", "misc", "easy to lift"),
        Word("HARD", "misc", "resistant to touch"),
        Word("SOFT", "misc", "yielding to touch"),
        Word("SMOOTH", "misc", "no rough edges"),
        Word("ROUGH", "misc", "bumpy to touch"),
        Word("SHARP", "misc", "with a fine edge"),
        Word("BLUNT", "misc", "without an edge"),
        Word("HOT", "misc", "high temperature"),
        Word("COLD", "misc", "low temperature"),
        Word("WARM", "misc", "mildly hot"),
        Word("COOL", "misc", "mildly cold"),
        Word("WET", "misc", "covered in water"),
        Word("DRY", "misc", "without water"),
        Word("CLEAN", "misc", "without dirt"),
        Word("DIRTY", "misc", "covered in mess"),
        Word("EMPTY", "misc", "with nothing in"),
        Word("FULL", "misc", "with everything in"),
        Word("OPEN", "misc", "not closed"),
        Word("CLOSED", "misc", "not open"),
        Word("NEW", "misc", "just made"),
        Word("OLD", "misc", "made long ago"),
        Word("YOUNG", "misc", "not many years"),
        Word("ANCIENT", "misc", "from long ago"),
        Word("FRESH", "misc", "newly made"),
        Word("STALE", "misc", "gone off"),
        Word("SWEET", "misc", "sugary flavor"),
        Word("SOUR", "misc", "sharp flavor"),
        Word("BITTER", "misc", "the coffee flavor"),
        Word("SALTY", "misc", "the sea flavor"),
        Word("SPICY", "misc", "the chili flavor"),
        Word("BLAND", "misc", "no strong flavor")
    )

    private const val RECENT_COOLDOWN = 40
    private val recent = ArrayDeque<String>(RECENT_COOLDOWN + 1)

    /**
     * Picks a word, avoiding the last [RECENT_COOLDOWN] words that have been
     * returned. Prevents the "half an hour in, same words keep coming back"
     * pattern that lets players win every round from memory.
     */
    fun random(): Word {
        val available = words.filter { it.text !in recent }
            .ifEmpty { words } // pool exhausted (shouldn't happen at this size) — fall back
        val chosen = available.random()
        recent.addLast(chosen.text)
        while (recent.size > RECENT_COOLDOWN) recent.removeFirst()
        return chosen
    }
}
